Update Dockerfile and bump GLIBC_VERSION to 2.25
sdurrheimer/alpine-glibc pull request #2
Opened 2017-04-07 13:44 UTC by sam-caldwell

Bumping glibc version to 2.25

2017-04-07 13:47 UTC, sam-caldwell commented
sdurrheimer, since 2.25 is released, I thought I would bump the version here so the docker image will pass security scans complaining about vulnerabilities since 2.23.

2017-04-07 13:50 UTC, sdurrheimer requested changes
Thanks you !

Could you also change the github repo url given that it has been moved to `sgerrand/alpine-pkg-glibc`.

2017-04-07 13:50 UTC, sdurrheimer commented on Dockerfile
> +ENV GLIBC_VERSION="2.25-r1"
`2.25-r0` given that `2.25-r1` is still a pre-release.

2017-04-07 16:05 UTC, sam-caldwell commented
Change was submitted as requested.

2017-06-05 06:38 UTC, sdurrheimer approved these changes

2017-06-05 06:38 UTC, sdurrheimer commented
Sorry for the delay.

2017-06-05 06:39 UTC, merged